/*******************************************************************************
 * Copyright [2015] [Onboard team of SERC, Peking University]
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *******************************************************************************/
package com.onboard.domain.mapper.model;

import com.onboard.domain.mapper.model.common.BaseItem;

import java.util.Date;

public class DocumentHistoryObject implements BaseItem {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column document_history.id
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column document_history.documentId
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    private Integer documentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column document_history.version
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    private String version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column document_history.updaterId
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    private Integer updaterId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column document_history.updaterName
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    private String updaterName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column document_history.created
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    private Date created;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column document_history.note
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    private String note;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column document_history.projectId
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    private Integer projectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column document_history.title
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column document_history.content
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column document_history.id
     *
     * @return the value of document_history.id
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column document_history.id
     *
     * @param id the value for document_history.id
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column document_history.documentId
     *
     * @return the value of document_history.documentId
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public Integer getDocumentId() {
        return documentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column document_history.documentId
     *
     * @param documentId the value for document_history.documentId
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public void setDocumentId(Integer documentId) {
        this.documentId = documentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column document_history.version
     *
     * @return the value of document_history.version
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public String getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column document_history.version
     *
     * @param version the value for document_history.version
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public void setVersion(String version) {
        this.version = version == null ? null : version.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column document_history.updaterId
     *
     * @return the value of document_history.updaterId
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public Integer getUpdaterId() {
        return updaterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column document_history.updaterId
     *
     * @param updaterId the value for document_history.updaterId
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public void setUpdaterId(Integer updaterId) {
        this.updaterId = updaterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column document_history.updaterName
     *
     * @return the value of document_history.updaterName
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public String getUpdaterName() {
        return updaterName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column document_history.updaterName
     *
     * @param updaterName the value for document_history.updaterName
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public void setUpdaterName(String updaterName) {
        this.updaterName = updaterName == null ? null : updaterName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column document_history.created
     *
     * @return the value of document_history.created
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column document_history.created
     *
     * @param created the value for document_history.created
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column document_history.note
     *
     * @return the value of document_history.note
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column document_history.note
     *
     * @param note the value for document_history.note
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column document_history.projectId
     *
     * @return the value of document_history.projectId
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public Integer getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column document_history.projectId
     *
     * @param projectId the value for document_history.projectId
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public void setProjectId(Integer projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column document_history.title
     *
     * @return the value of document_history.title
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column document_history.title
     *
     * @param title the value for document_history.title
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column document_history.content
     *
     * @return the value of document_history.content
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column document_history.content
     *
     * @param content the value for document_history.content
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table document_history
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public DocumentHistoryObject(DocumentHistoryObject parent) {
        this.id = parent.getId();
        this.documentId = parent.getDocumentId();
        this.version = parent.getVersion();
        this.updaterId = parent.getUpdaterId();
        this.updaterName = parent.getUpdaterName();
        this.created = parent.getCreated();
        this.note = parent.getNote();
        this.projectId = parent.getProjectId();
        this.title = parent.getTitle();
        this.content = parent.getContent();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table document_history
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public DocumentHistoryObject() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table document_history
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public DocumentHistoryObject(int id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table document_history
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    @Override
    public DocumentHistoryObject copy() {
        return new DocumentHistoryObject(this);
    }
}