package com.onboard.domain.mapper.model;

import com.onboard.domain.mapper.model.common.BaseItem;

public class GithubInfoObject implements BaseItem {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column github_info.id
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column github_info.userId
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column github_info.code
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column github_info.token
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    private String token;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column github_info.userName
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column github_info.userEmail
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    private String userEmail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column github_info.deleted
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    private Boolean deleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column github_info.onboardUserId
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    private Integer onboardUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column github_info.type
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    private String type;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column github_info.id
     *
     * @return the value of github_info.id
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column github_info.id
     *
     * @param id the value for github_info.id
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column github_info.userId
     *
     * @return the value of github_info.userId
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column github_info.userId
     *
     * @param userId the value for github_info.userId
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column github_info.code
     *
     * @return the value of github_info.code
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column github_info.code
     *
     * @param code the value for github_info.code
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column github_info.token
     *
     * @return the value of github_info.token
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public String getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column github_info.token
     *
     * @param token the value for github_info.token
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public void setToken(String token) {
        this.token = token == null ? null : token.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column github_info.userName
     *
     * @return the value of github_info.userName
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column github_info.userName
     *
     * @param userName the value for github_info.userName
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column github_info.userEmail
     *
     * @return the value of github_info.userEmail
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public String getUserEmail() {
        return userEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column github_info.userEmail
     *
     * @param userEmail the value for github_info.userEmail
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public void setUserEmail(String userEmail) {
        this.userEmail = userEmail == null ? null : userEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column github_info.deleted
     *
     * @return the value of github_info.deleted
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public Boolean getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column github_info.deleted
     *
     * @param deleted the value for github_info.deleted
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column github_info.onboardUserId
     *
     * @return the value of github_info.onboardUserId
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public Integer getOnboardUserId() {
        return onboardUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column github_info.onboardUserId
     *
     * @param onboardUserId the value for github_info.onboardUserId
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public void setOnboardUserId(Integer onboardUserId) {
        this.onboardUserId = onboardUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column github_info.type
     *
     * @return the value of github_info.type
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column github_info.type
     *
     * @param type the value for github_info.type
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table github_info
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public GithubInfoObject(GithubInfoObject parent) {
        this.id = parent.getId();
        this.userId = parent.getUserId();
        this.code = parent.getCode();
        this.token = parent.getToken();
        this.userName = parent.getUserName();
        this.userEmail = parent.getUserEmail();
        this.deleted = parent.getDeleted();
        this.onboardUserId = parent.getOnboardUserId();
        this.type = parent.getType();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table github_info
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public GithubInfoObject() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table github_info
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public GithubInfoObject(int id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table github_info
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public GithubInfoObject(boolean deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table github_info
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public GithubInfoObject(int id, boolean deleted) {
        this.id = id;
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table github_info
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    @Override
    public GithubInfoObject copy() {
        return new GithubInfoObject(this);
    }
}