package com.onboard.domain.mapper.model;

import com.onboard.domain.mapper.model.common.BaseItem;

import java.util.Date;

public class TodoDurationObject implements BaseItem {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column todo_duration.id
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column todo_duration.projectId
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    private Integer projectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column todo_duration.companyId
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    private Integer companyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column todo_duration.todoId
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    private Integer todoId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column todo_duration.creatorId
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    private Integer creatorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column todo_duration.startTime
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    private Date startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column todo_duration.endTime
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    private Date endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column todo_duration.creatorName
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    private String creatorName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column todo_duration.creatorAvatar
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    private String creatorAvatar;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column todo_duration.id
     *
     * @return the value of todo_duration.id
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column todo_duration.id
     *
     * @param id the value for todo_duration.id
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column todo_duration.projectId
     *
     * @return the value of todo_duration.projectId
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public Integer getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column todo_duration.projectId
     *
     * @param projectId the value for todo_duration.projectId
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public void setProjectId(Integer projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column todo_duration.companyId
     *
     * @return the value of todo_duration.companyId
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public Integer getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column todo_duration.companyId
     *
     * @param companyId the value for todo_duration.companyId
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public void setCompanyId(Integer companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column todo_duration.todoId
     *
     * @return the value of todo_duration.todoId
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public Integer getTodoId() {
        return todoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column todo_duration.todoId
     *
     * @param todoId the value for todo_duration.todoId
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public void setTodoId(Integer todoId) {
        this.todoId = todoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column todo_duration.creatorId
     *
     * @return the value of todo_duration.creatorId
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public Integer getCreatorId() {
        return creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column todo_duration.creatorId
     *
     * @param creatorId the value for todo_duration.creatorId
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public void setCreatorId(Integer creatorId) {
        this.creatorId = creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column todo_duration.startTime
     *
     * @return the value of todo_duration.startTime
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column todo_duration.startTime
     *
     * @param startTime the value for todo_duration.startTime
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column todo_duration.endTime
     *
     * @return the value of todo_duration.endTime
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column todo_duration.endTime
     *
     * @param endTime the value for todo_duration.endTime
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column todo_duration.creatorName
     *
     * @return the value of todo_duration.creatorName
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public String getCreatorName() {
        return creatorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column todo_duration.creatorName
     *
     * @param creatorName the value for todo_duration.creatorName
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public void setCreatorName(String creatorName) {
        this.creatorName = creatorName == null ? null : creatorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column todo_duration.creatorAvatar
     *
     * @return the value of todo_duration.creatorAvatar
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public String getCreatorAvatar() {
        return creatorAvatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column todo_duration.creatorAvatar
     *
     * @param creatorAvatar the value for todo_duration.creatorAvatar
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public void setCreatorAvatar(String creatorAvatar) {
        this.creatorAvatar = creatorAvatar == null ? null : creatorAvatar.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todo_duration
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public TodoDurationObject(TodoDurationObject parent) {
        this.id = parent.getId();
        this.projectId = parent.getProjectId();
        this.companyId = parent.getCompanyId();
        this.todoId = parent.getTodoId();
        this.creatorId = parent.getCreatorId();
        this.startTime = parent.getStartTime();
        this.endTime = parent.getEndTime();
        this.creatorName = parent.getCreatorName();
        this.creatorAvatar = parent.getCreatorAvatar();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todo_duration
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public TodoDurationObject() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todo_duration
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public TodoDurationObject(int id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todo_duration
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    @Override
    public TodoDurationObject copy() {
        return new TodoDurationObject(this);
    }
}